//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch brainbay.rc
//
#define IDS_STRING1                     1
#define IDC_MYICON                      2
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_SMALL                       108
#define IDC_MAINMENU                    109
#define IDD_EEGBOX                      129
#define IDD_EEGBOX_CHANSELECT           129
#define IDD_MIDISTREAMBOX               139
#define IDD_TRANSLATEBOX                140
#define IDD_FFTPROPBOX                  144
#define IDD_FILTERBOX                   145
#define IDI_ICON2                       146
#define IDD_PARTICLEBOX                 147
#define IDD_THRESHOLDBOX                151
#define IDD_OSCIBOX                     167
#define IDD_SIGNALBOX                   169
#define IDD_MAGNITUDEBOX                175
#define IDD_EDITCOLORBOX                178
#define IDD_EDITSCALEBOX                179
#define IDD_WAVBOX                      180
#define IDD_TCP_RECEIVEBOX              182
#define IDD_STATUSBOX                   183
#define IDD_SETTINGSBOX                 184
#define IDI_MYEEG                       185
#define IDD_DOKUBOX                     186
#define IDD_EVALBOX                     187
#define IDD_AVIPROPBOX                  188
#define IDD_AVERAGEBOX                  189
#define IDD_CORRBOX                     190
#define IDD_CONNECTBOX                  191
#define IDD_EDF_WRITERBOX               192
#define IDD_OUTPORTBOX                  193
#define IDD_INPORTBOX                   194
#define IDD_TCP_SENDERBOX               195
#define IDD_EDF_READERBOX               196
#define IDD_COMPAREBOX                  197
#define IDD_BALLGAMEBOX                 198
#define IDD_MIXER4BOX                   201
#define IDD_MOUSEBOX                    202
#define IDD_ERPDETECTBOX                203
#define IDD_COM_WRITERBOX               204
#define IDD_CAMBOX                      205
#define IDD_DEBOUNCEBOX                 208
#define IDD_INTEGRATEBOX                209
#define IDD_CONSTANTBOX                 210
#define IDD_SAMPLE_HOLDBOX              211
#define IDD_CLICKSELECTOR               212
#define IDD_MATLABBOX                   213
#define IDD_COUNTERBOX                  214
#define IDD_SKINDIALOGBOX               215
#define IDD_FILE_WRITERBOX              216
#define IDD_DEVIATIONBOX                217
#define IDD_TAGBOX                      218
#define IDD_MCIPROPBOX                  219
#define IDD_KEYSTRIKEBOX                222
#define IDD_PEAKDETECTBOX               223
#define IDD_SPELLERBOX                  224
#define IDD_ANDBOX                      225
#define IDD_ORBOX                       226
#define IDD_NOTBOX                      227
#define IDD_MARTINIBOX                  228
#define IDD_FILE_READERBOX              229
#define IDD_PORTBOX                     230
#define IDD_ARRAY3600                   231
#define IDC_CURSOR1                     232
#define IDC_CURSOR2                     233
#define IDC_CURSOR3                     234
#define IDC_CURSOR4                     235
#define IDC_CURSOR5                     236
#define IDC_CURSOR6                     237
#define IDD_COMREADER                   238
#define IDD_OPTIMABOX                   239
#define IDD_NEUROBITBOX                 239
#define IDD_DELAYBOX                    241
#define IDD_LIMITERBOX                  242
#define IDD_EMOTIVBOX                   243
#define IDD_FLOATVECTOR                 244
#define IDD_VECTORFLOAT                 245
#define IDD_DISPLAYVECTOR               246
#define IDD_VECTORBUFFER                247
#define IDD_EEGBOX_IBVA                 248
#define IDD_EEGBOX_NIA                  249
#define IDD_EEGBOX_GENERIC              250
#define IDD_EEGBOX_SBT2                 251
#define IDD_GANGLIONBOX                 254
#define IDD_SESSIONTIMEBOX              255
#define IDD_SESSIONMANAGERBOX           256
#define IDD_KEYCAPTUREBOX               257
#define IDD_BUTTONBOX                   258
#define IDD_EVALBOX_ML                  259
#define IDD_SHADOWBOX                   260
#define IDD_OSC_SENDERBOX               261
#define IDD_BIOSEMIBOX                  262
#define IDD_BRAINFLOWBOX                266
#define IDC_PORTCOMBO                   1000
#define IDC_BAUDCOMBO                   1001
#define IDC_DEVICECOMBO                 1002
#define IDC_FILEMODECOMBO               1003
#define IDC_SAMPLINGCOMBO               1004
#define IDC_SIGNALCOMBO                 1008
#define IDC_STARTBAND                   1010
#define IDC_ENDBAND                     1011
#define IDC_FFTDRAWINTERVAL             1012
#define IDC_FFTSCALE                    1013
#define IDC_PALETTEFILE                 1014
#define IDC_CHN3                        1014
#define IDC_CHN4                        1015
#define IDC_GAINX                       1015
#define IDC_GAINY                       1016
#define IDC_GAINZ                       1017
#define IDC_AVGINTERVAL                 1021
#define IDC_MIDIINSTCOMBO               1022
#define IDC_ADAPTINTERVAL               1022
#define IDC_AVGINTERVALBAR              1024
#define IDC_MIDICHANGESCHECK            1030
#define IDC_MIDICHN                     1032
#define IDC_MIDITONEBUF                 1033
#define IDC_MIDITIMER                   1034
#define IDC_AVGGAIN                     1034
#define IDC_MIDITONEBUFBAR              1035
#define IDC_MIDITIMERBAR                1036
#define IDC_AVGFROM                     1037
#define IDC_AVGTO                       1038
#define IDC_MIDIMUTE                    1039
#define IDC_MIDIMUTEONFALSE             1040
#define IDC_MIDIVOLUMEFROM              1041
#define IDC_MIDIVOLUMETO                1042
#define IDC_PAR1TEXT                    1044
#define IDC_PAR2TEXT                    1045
#define IDC_PAR1TEXT2                   1046
#define IDC_AVGFROMBAR                  1047
#define IDC_AVGTOBAR                    1048
#define IDC_PAR2TEXT2                   1049
#define IDC_PAR1TEXT3                   1050
#define IDC_AVGGAINBAR                  1051
#define IDC_PAR1TEXT4                   1051
#define IDC_HARMONICLIST                1052
#define IDC_ADAPTINTERVALBAR            1052
#define IDC_PAR1TEXT5                   1052
#define IDC_PAR1TEXT6                   1053
#define IDC_SAVEHARMONIC                1054
#define IDC_PAR1TEXT7                   1054
#define IDC_HARMONICNAME                1056
#define IDC_LOADHARMONIC                1057
#define IDC_PITCHRANGE                  1058
#define IDC_TONEBAR                     1059
#define IDC_PITCHINTERVAL               1059
#define IDC_ADDTONE                     1060
#define IDC_DELTONE                     1061
#define IDC_ACTTONE                     1063
#define IDC_HARMONICCLEAR               1064
#define IDC_VALUEBAR                    1066
#define IDC_FFTALIGNCOMBO               1072
#define IDC_WINDOWCOMBO                 1073
#define IDC_FFTCOLOR1                   1074
#define IDC_BINCOMBO                    1074
#define IDC_FFTBKCOLOR                  1075
#define IDC_FFTCOLOR2                   1076
#define IDC_FFTKINDCOMBO                1076
#define IDC_LOADPAL                     1077
#define IDC_SAVEPAL                     1078
#define IDC_FFTCOLOR3                   1079
#define IDC_FILTERNEWNAME               1084
#define IDC_FILTERSTORE                 1085
#define IDC_FROMFREQ                    1086
#define IDC_TOFREQ                      1087
#define IDC_FILTERPAR0                  1089
#define IDC_FILTERPAR1                  1090
#define IDC_FILTERPAR2                  1091
#define IDC_FILTERTYPECOMBO             1092
#define IDC_PAR1CAPT                    1094
#define IDC_PAR2CAPT                    1095
#define IDC_PAR0CAPT                    1097
#define IDC_MIDIPORTCOMBO               1098
#define IDC_VALUE                       1099
#define IDC_DATA2                       1100
#define IDC_PARTICLEMUTE                1121
#define IDC_FFTCAPTIONS                 1122
#define IDC_FFTDRAWINTERVALBAR          1124
#define IDC_FFTSCALEBAR                 1125
#define IDC_OSCISPEEDBAR                1125
#define IDC_OSCISPEED                   1126
#define IDC_CHN3BAR                     1126
#define IDC_GAINXBAR                    1126
#define IDC_FREQUENCYBAR                1127
#define IDC_OSCIGAINBAR                 1127
#define IDC_CHN4BAR                     1127
#define IDC_GAINYBAR                    1127
#define IDC_GAINBAR                     1128
#define IDC_OSCIGAIN                    1128
#define IDC_GAINZBAR                    1128
#define IDC_GAIN                        1129
#define IDC_FREQUENCY                   1130
#define IDC_MULTIPLY                    1131
#define IDC_PHASE                       1131
#define IDC_IN_MIN                      1131
#define IDC_ADD                         1132
#define IDC_PHASEBAR                    1132
#define IDC_OUT_MIN                     1132
#define IDC_CENTER                      1133
#define IDC_IN_MAX                      1133
#define IDC_WIDTH                       1134
#define IDC_OUT_MAX                     1134
#define IDC_NOISE                       1134
#define IDC_NOISEBAR                    1135
#define IDC_ACT_INPUT                   1135
#define IDC_STORE                       1136
#define IDC_ACT_OUTPUT                  1136
#define IDC_PASSTYPECOMBO               1137
#define IDC_ORDER                       1138
#define IDC_WIDTHBAR                    1140
#define IDC_CENTERBAR                   1141
#define IDC_PARAMETERCOMBO              1143
#define IDC_REMOTECOMBO                 1144
#define IDC_MINLABEL                    1145
#define IDC_MAXLABEL                    1146
#define IDC_SETMIN                      1147
#define IDC_SETMAX                      1148
#define IDC_RESETMINMAX                 1149
#define IDC_AND                         1150
#define IDC_OR                          1151
#define IDC_SECONDS                     1152
#define IDC_SHOWSECONDS                 1152
#define IDC_GRID                        1153
#define IDC_LINE                        1154
#define IDC_CONNECTED                   1155
#define IDC_WITHIN                      1155
#define IDC_OPEN_ARCHIVE                1156
#define IDC_GROUP                       1156
#define IDC_REC_ARCHIVE                 1157
#define IDC_GRADUAL                     1157
#define IDC_CLOSE_ARCHIVE               1158
#define IDC_SAVEBITMAP                  1158
#define IDC_ARCHIVE_FILENAME            1159
#define IDC_SAVEATEND                   1159
#define IDC_ARCHIVE_POSBAR              1160
#define IDC_SHOWMETER                   1161
#define IDC_STOP_ARCHIVE                1161
#define IDC_FLOW_CONTROL                1161
#define IDC_SELECTCOLOR                 1162
#define IDC_PLAY_ARCHIVE                1162
#define IDC_RISING                      1163
#define IDC_STATUS                      1163
#define IDC_STOP_COM                    1163
#define IDC_FALLING                     1164
#define IDC_PLAY_COM                    1164
#define IDC_CLOSE_REC                   1164
#define IDC_CENTERED                    1165
#define IDC_FONTCOL                     1165
#define IDC_SAMPLINGRATE                1166
#define IDC_OPENWAVFILE                 1166
#define IDC_FONTBKCOL                   1166
#define IDC_BKCOL                       1166
#define IDC_WAVFILENAME                 1167
#define IDC_TIME                        1167
#define IDC_DIALOGINTERVAL              1167
#define IDC_USE_MEDIAN                  1167
#define IDC_WAVLENGTH                   1168
#define IDC_JUMPPOS                     1168
#define IDC_DRAWINTERVAL                1168
#define IDC_BASELINE                    1168
#define IDC_WAVREPINTERVAL              1169
#define IDC_CONNECT                     1169
#define IDC_SESSLEN                     1169
#define IDC_EMOTIV_PATH                 1169
#define IDC_WAVCHANGESONLY              1170
#define IDC_CLOSE                       1170
#define IDC_SESSTART                    1170
#define IDC_TESTBAT                     1170
#define IDC_GANGLION_PATH               1170
#define IDC_WAVVOLUMEINPUTFROM          1171
#define IDC_LIST                        1171
#define IDC_DBG                         1171
#define IDC_TESTBAT2                    1171
#define IDC_SETCUTOFF                   1171
#define IDC_STARTDESIGN_PATH            1171
#define IDC_WAVVOLUMEINPUTTO            1172
#define IDC_PATIENT                     1172
#define IDC_WAVVOLUMEFROMBAR            1173
#define IDC_CHANNELS                    1173
#define IDC_WAVVOLUMEFROM               1174
#define IDC_DURATION                    1174
#define IDC_WAVVOLUMETOBAR              1175
#define IDC_SAMPLES                     1175
#define IDC_WAVVOLUMETO                 1176
#define IDC_HOST                        1176
#define IDC_WAVMUTE                     1177
#define IDC_CHANNELCOMBO                1177
#define IDC_PORT                        1177
#define IDC_WAVTIMESREPEAT              1178
#define IDC_PHYSMIN                     1178
#define IDC_WAVBUFSIZE                  1178
#define IDC_ROUTE                       1178
#define IDC_WAVSPEEDCENTER              1179
#define IDC_DIGMIN                      1179
#define IDC_SENDINTERVAL                1179
#define IDC_WAVSPEEDFACTOR              1180
#define IDC_PHYSMAX                     1180
#define IDC_WAVLOW                      1181
#define IDC_DIGMAX                      1181
#define IDC_WAVHIGH                     1182
#define IDC_PHYSDIM                     1182
#define IDC_WAVLOWHIGH                  1183
#define IDC_ELECTRODE                   1183
#define IDC_WAVREVERSE                  1184
#define IDC_DEVICE                      1184
#define IDC_WATCH                       1185
#define IDC_SEGMENTS                    1186
#define IDC_MIDIPORTLIST                1186
#define IDC_SAVESETTINGS                1187
#define IDC_EMPTY                       1187
#define IDC_STOP                        1188
#define IDC_NEWSAMPLINGRATE             1188
#define IDC_DOKU                        1189
#define IDC_SELECTCOMBO                 1189
#define IDC_ENABLEMIDI                  1189
#define IDC_EVALAPPLY                   1190
#define IDC_EVALEXPRESSION              1191
#define IDC_RUNSESSION                  1195
#define IDC_AVIFILE                     1196
#define IDC_STOPSESSION                 1196
#define IDC_LOADAVI                     1197
#define IDC_DESIGN                      1197
#define IDC_AVERAGEINTERVALBAR          1198
#define IDC_JUMP                        1198
#define IDC_AVERAGEINTERVAL             1199
#define IDC_RESETBUTTON                 1199
#define IDC_CORRINTERVALBAR             1200
#define IDC_FLY                         1200
#define IDC_CORRINTERVAL                1201
#define IDC_ENDSESSION                  1201
#define IDC_BIGADAPT                    1204
#define IDC_ADAPT_LOWERLIMIT            1204
#define IDC_SMALLADAPT                  1205
#define IDC_MIN                         1205
#define IDC_ADAPT_UPPERLIMIT            1205
#define IDC_METERCAPTION                1206
#define IDC_MAX                         1207
#define IDC_FROM                        1210
#define IDC_TO                          1211
#define IDC_DIMCOMBO                    1212
#define IDC_EDFFILE                     1216
#define IDC_SELECT                      1217
#define IDC_LABEL                       1218
#define IDC_GENTESTFILE                 1218
#define IDC_SPP                         1219
#define IDC_PREFILTERING                1220
#define IDC_START                       1221
#define IDC_NORMAL                      1222
#define IDC_DESC                        1223
#define IDC_SWEET                       1223
#define IDC_CAPTION                     1224
#define IDC_DRY                         1224
#define IDC_DIMENSION                   1225
#define IDC_PUMP1                       1225
#define IDC_RANGEPORTCOMBO              1226
#define IDC_PUMP2                       1226
#define IDC_GETRANGE                    1227
#define IDC_QUICKIE                     1227
#define IDC_PAUSE                       1231
#define IDC_CMD                         1233
#define IDC_SENDCMD                     1234
#define IDC_POS                         1236
#define IDC_FROMREDBAR                  1238
#define IDC_FROMGREENBAR                1239
#define IDC_TOREDBAR                    1240
#define IDC_BKCOLOR                     1240
#define IDC_TOGREENBAR                  1241
#define IDC_SIGCOMBO                    1241
#define IDC_TOBLUEBAR                   1242
#define IDC_SIGCOLOR                    1242
#define IDC_ENABLE_IN                   1242
#define IDC_FROMBLUEBAR                 1243
#define IDC_GRIDCOLOR                   1243
#define IDC_GREATER                     1243
#define IDC_CAPTCOLOR                   1244
#define IDC_GREATEREQUAL                1244
#define IDC_SPEEDBAR                    1244
#define IDC_SPEED                       1245
#define IDC_LESS                        1245
#define IDC_RACKETBAR                   1246
#define IDC_LESSEQUAL                   1246
#define IDC_CHN1                        1246
#define IDC_EQUAL                       1247
#define IDC_RACKET                      1247
#define IDC_CHN2                        1247
#define IDC_SOLO1                       1248
#define IDC_QCHN3                       1248
#define IDC_SOLO2                       1249
#define IDC_QCHN4                       1249
#define IDC_SOLO3                       1250
#define IDC_SOLO4                       1251
#define IDC_COMVOLT                     1251
#define IDC_CHN1BAR                     1252
#define IDC_CHN2BAR                     1253
#define IDC_XACCBAR                     1254
#define IDC_DWELLTIMEBAR                1254
#define IDC_YACCBAR                     1255
#define IDC_DWELLRADIUSBAR              1255
#define IDC_XACC                        1256
#define IDC_DWELLTIME                   1256
#define IDC_YACC                        1257
#define IDC_DWELLRADIUS                 1257
#define IDC_RESETRADIUSBAR              1258
#define IDC_STARTUP                     1259
#define IDC_RESETRADIUS                 1259
#define IDC_EPOCHS                      1260
#define IDC_AUTORUN                     1260
#define IDC_PRESTIM                     1261
#define IDC_MINIMIZED                   1261
#define IDC_STARTCAPTURE                1262
#define IDC_ADDARCHIVETIME              1262
#define IDC_LENGTH                      1263
#define IDC_SESSIONPOS                  1263
#define IDC_STARTDESIGN                 1263
#define IDC_STOPCAPTURE                 1264
#define IDC_XINC                        1264
#define IDC_LOCKSESSION                 1264
#define IDC_SAVEERP                     1265
#define IDC_YINC                        1265
#define IDC_LOADERP                     1266
#define IDC_XMAX                        1266
#define IDC_ERPFILENAME                 1267
#define IDC_YMAX                        1267
#define IDC_SENDCOMMAND                 1268
#define IDC_ACT_X                       1268
#define IDC_TRIGGER                     1269
#define IDC_YMAX2                       1269
#define IDC_ACT_Y                       1269
#define IDC_COMMAND                     1270
#define IDC_RESET                       1271
#define IDC_BYPASS                      1273
#define IDC_DATA1                       1274
#define IDC_ENABLE_DWELLING             1274
#define IDC_INITCAM                     1275
#define IDC_AUTODETECT                  1275
#define IDC_EXITCAM                     1276
#define IDC_BYPASS_POS                  1276
#define IDC_AUTOINIT                    1277
#define IDC_NIGHTMODE                   1279
#define IDC_SAVE_POINTS                 1280
#define IDC_LIST2                       1281
#define IDC_CAMSTATUS                   1283
#define IDC_AUTORESTORE                 1284
#define IDC_SETTINGS                    1285
#define IDC_UPDATERATE                  1287
#define IDC_CUR_RATE                    1288
#define IDC_THRESHOLD_TIME              1289
#define IDC_DTIME                       1291
#define IDC_APPLY                       1292
#define IDC_SAMPLE                      1294
#define IDC_HOLD                        1295
#define IDC_SETSTART                    1297
#define IDC_SETEND                      1298
#define IDC_SETDOUBLE                   1298
#define IDC_SETRIGHT                    1299
#define IDC_GOSTART                     1299
#define IDC_SETDRAG                     1300
#define IDC_NEXTCLICK                   1301
#define IDC_SELACTIVE                   1302
#define IDC_ERROR                       1303
#define IDC_ERROR_DIST                  1303
#define IDC_CH1                         1304
#define IDC_ERROR_ANGLE                 1304
#define IDC_CH2                         1305
#define IDC_PT1X                        1305
#define IDC_CH3                         1306
#define IDC_PT1Y                        1306
#define IDC_CH4                         1307
#define IDC_CH5                         1308
#define IDC_CH6                         1309
#define IDC_PT2X                        1309
#define IDC_BIDIRECT                    1310
#define IDC_PT2Y                        1310
#define IDC_OFFSET                      1311
#define IDC_APPLYOFFSET                 1312
#define IDC_EXTEND                      1313
#define IDC_RESOLUTION                  1314
#define IDC_HIDE                        1315
#define IDC_BATTERY                     1315
#define IDC_RESOLUTION2                 1315
#define IDC_MATLABINTERVALBAR           1316
#define IDC_CUTOFF                      1316
#define IDC_MATLABEXPRESSION            1317
#define IDC_MATLABINTERVAL              1318
#define IDC_MATLABAPPLY                 1319
#define IDC_MATLABTRANSFER              1320
#define IDC_CALLPERIODIC                1321
#define IDC_COUNTFT                     1322
#define IDC_COUNTTF                     1323
#define IDC_COUNTIV                     1324
#define IDC_SHOWCOUNTER                 1325
#define IDC_RESETCOUNTER                1326
#define IDC_RESETVALUE                  1327
#define IDC_RESETBEST                   1328
#define IDC_COUNTFREQ                   1329
#define IDC_SKINFILE                    1330
#define IDC_OPENSKIN                    1331
#define IDC_APPLYSKIN                   1332
#define IDC_OPENBITMAP                  1333
#define IDC_NOARCHIVE                   1334
#define IDC_NEXTBUTTON                  1334
#define IDC_RECORDARCHIVE               1335
#define IDC_CREATEBUTTON                1335
#define IDC_PLAYARCHIVE                 1336
#define IDC_DELETEBUTTON                1336
#define IDC_ENABLE_TRACKING             1337
#define IDC_NEXTSLIDER                  1337
#define IDC_ARCHIVEFILE                 1338
#define IDC_CREATESLIDER                1338
#define IDC_FILESTATUS                  1339
#define IDC_DELETESLIDER                1339
#define IDC_TRACKFACE                   1339
#define IDC_FILENAME                    1340
#define IDC_FORMATCOMBO                 1341
#define IDC_DEVIATIONINTERVALBAR        1342
#define IDC_HEADERLINE                  1342
#define IDC_DEVIATIONINTERVAL           1343
#define IDC_FONTSIZEBAR                 1344
#define IDC_BARSIZEBAR                  1345
#define IDC_COMMABAR                    1345
#define IDC_DIGITSBAR                   1345
#define IDC_BITMAPSIZEBAR               1345
#define IDC_FONTSIZE                    1346
#define IDC_FONTCOLOR                   1347
#define IDC_BARSIZE                     1347
#define IDC_BITMAPSIZE                  1347
#define IDC_INTEGER                     1348
#define IDC_DIGITS                      1349
#define IDC_TAG                         1350
#define IDC_TIMEFORMAT                  1350
#define IDC_TYPE                        1351
#define IDC_SIZEBAR                     1353
#define IDC_MCIFILE                     1354
#define IDC_OPEN                        1355
#define IDC_MCIPLAY                     1356
#define IDC_MCISTOP                     1357
#define IDC_MCIPLUS                     1358
#define IDC_MCIMINUS                    1359
#define IDC_UPDATESPEED                 1360
#define IDC_LOAD                        1361
#define IDC_SPEEDUPDATEBAR              1362
#define IDC_UPDATEVOLUME                1363
#define IDC_POS_CENTER                  1363
#define IDC_VOLUMEUPDATEBAR             1364
#define IDC_KEY                         1369
#define IDC_ADDKEYUP                    1370
#define IDC_ADDKEYDOWN                  1371
#define IDC_KEYLIST                     1372
#define IDC_KEYCOMBO                    1373
#define IDC_BITMAPFILENAME              1377
#define IDC_BUTTONNAME                  1378
#define IDC_BUTTONPARAM                 1379
#define IDC_SLIDERNAME                  1380
#define IDC_BUTTONTYPE1                 1382
#define IDC_BUTTONTYPE2                 1383
#define IDC_BUTTONTYPE3                 1384
#define IDC_BUTTONTYPE4                 1385
#define IDC_SLIDERTYPE1                 1386
#define IDC_SLIDERTYPE2                 1387
#define IDC_SLIDERTYPE3                 1388
#define IDC_SET                         1389
#define IDC_XPOS                        1391
#define IDC_YPOS                        1392
#define IDC_PARAMNAME                   1393
#define IDC_METHODCOMBO                 1394
#define IDC_BUTTONTYPE5                 1394
#define IDC_PREV                        1395
#define IDC_NEXT                        1396
#define IDC_SIGCAPTION                  1397
#define IDC_STARTSTREAM                 1398
#define IDC_STOPSTREAM                  1399
#define IDC_TOPS                        1399
#define IDC_VALLEYS                     1400
#define IDC_BOTH                        1401
#define IDC_MEMORY                      1402
#define IDC_SHOWLIVE                    1403
#define IDC_SESSIONLOOP                 1410
#define IDC_SWITCHTIME                  1411
#define IDC_PRESSTIME                   1412
#define IDC_MODECOMBO                   1413
#define IDC_IMPORTLIST                  1414
#define IDC_WORDFILE                    1415
#define IDC_MIDDLE                      1416
#define IDC_IDLETIME                    1416
#define IDC_LEARN                       1417
#define IDC_NEWWORDS                    1418
#define IDC_LOADDICT                    1419
#define IDC_DICTFILE                    1420
#define IDC_SAVEDICT                    1421
#define IDC_EXPORTLIST                  1422
#define IDC_AUTOLEARN                   1423
#define IDC_CLEARDICT                   1424
#define IDC_WORDCOUNT                   1425
#define IDC_TEST                        1426
#define IDC_DIRECTSEND                  1426
#define IDC_BINARY                      1427
#define IDC_BITS                        1430
#define IDC_ONE                         1432
#define IDC_OPENFILE                    1437
#define IDC_TRG_MANUAL                  1438
#define IDC_TRG_RISING                  1439
#define IDC_TRG_FALLING                 1440
#define IDC_GAMETIMEBAR                 1443
#define IDC_GAMETIME                    1444
#define IDC_WRITEVAL0                   1446
#define IDC_VAL0                        1447
#define IDC_VAL1                        1448
#define IDC_WRITEVAL1                   1449
#define IDC_PORTADDRESS                 1450
#define IDC_PORTADDRESSCOMBO            1451
#define IDC_PORTMODECOMBO               1452
#define IDC_PD0                         1453
#define IDC_PD1                         1454
#define IDC_INVAND                      1454
#define IDC_PD2                         1455
#define IDC_INVOR                       1455
#define IDC_PD3                         1456
#define IDC_INVIGNORE                   1456
#define IDC_PD4                         1457
#define IDC_SETNOW                      1457
#define IDC_PD5                         1458
#define IDC_PERIODIC                    1458
#define IDC_PD6                         1459
#define IDC_PERIOD                      1459
#define IDC_PD7                         1460
#define IDC_CONTROL_ON                  1460
#define IDC_CONTROL_OFF                 1461
#define IDC_MAXVOLTAGE                  1462
#define IDC_MAXCURRENT                  1463
#define IDC_RECEIVED                    1463
#define IDC_MAXPOWER                    1464
#define IDC_PROCESSED                   1464
#define IDC_RET_INVALID                 1464
#define IDC_VOLTAGE                     1465
#define IDC_RET_VALUE                   1465
#define IDC_MINTIME                     1465
#define IDC_ADDRESS                     1466
#define IDC_SENT                        1466
#define IDC_SENT2                       1467
#define IDC_ACTVALUE                    1467
#define IDC_SAVE_DEVCTX                 1468
#define IDC_LOAD_DEVCTX                 1469
#define IDC_DISPLAYSETTINGS             1470
#define IDC_SETTINGSFILE                1471
#define IDC_SHOW_EXTRACHANNELS          1471
#define IDC_QCHN1                       1472
#define IDC_QCHN2                       1473
#define IDC_NB_ARCHIVE_FILENAME         1474
#define IDC_NB_ARCHIVE_NAME             1474
#define IDC_OPEN_NB_ARCHIVE             1475
#define IDC_CLOSE_NB_ARCHIVE            1476
#define IDC_REC_NB_ARCHIVE              1477
#define IDC_NB_CLOSE_REC                1478
#define IDC_END_NB_REC                  1478
#define IDC_END_NB_RECORDING            1478
#define IDC_COMBO1                      1479
#define IDC_NB_DEVICECOMBO              1479
#define IDC_USERID_COMBO                1479
#define IDC_USE_VIDEOINPUT              1480
#define IDC_CHANSET                     1480
#define IDC_USE_CVCAPTURE               1481
#define IDC_BIOSEMI_OP1                 1481
#define IDC_BIOSEMI_OP2                 1482
#define IDC_RADIO2                      1483
#define IDC_BIOSEMI_OP3                 1483
#define IDC_CHNLABEL                    1484
#define IDC_BIOSEMI_OP4                 1484
#define IDC_RESLABEL                    1485
#define IDC_BIOSEMI_OP5                 1485
#define IDC_RESLABEL2                   1486
#define IDC_BIOSEMI_OP6                 1486
#define IDC_CHNFROMPORT                 1487
#define IDC_BIOSEMI_OP7                 1487
#define IDC_BIOSEMI_OP8                 1488
#define IDC_BIOSEMI_OP9                 1489
#define IDC_DELAYTIME                   1490
#define IDC_BIOSEMI_OP10                1490
#define IDC_LOWERLIMIT                  1491
#define IDC_BIOSEMI_OP11                1491
#define IDC_UPPERLIMIT                  1492
#define IDC_BIOSEMI_OP12                1492
#define IDC_APPEND                      1493
#define IDC_BIOSEMI_OP13                1493
#define IDC_PLAY_ONCE                   1494
#define IDC_ADD_DATE                    1494
#define IDC_BIOSEMI_OP14                1494
#define IDC_PLAY_ONCE2                  1495
#define IDC_VALUES                      1495
#define IDC_AUTOCREATE                  1495
#define IDC_BIOSEMI_OP15                1495
#define IDC_AUTOSTART                   1496
#define IDC_DEVICETYPE                  1496
#define IDC_SEMICOLON                   1496
#define IDC_BIOSEMI_OP16                1496
#define IDC_EMOTIV_ARCHIVE_NAME         1497
#define IDC_SBT2STATUS                  1497
#define IDC_OPEN_EMOTIV_ARCHIVE         1498
#define IDC_SCAN_GANGLION               1498
#define IDC_CLOSE_EMOTIV_ARCHIVE        1499
#define IDC_GANGLION_DEVICECOMBO        1499
#define IDC_REC_EMOTIV_ARCHIVE          1500
#define IDC_OPEN_GANGLION_ARCHIVE       1500
#define IDC_END_EMOTIV_RECORDING        1501
#define IDC_CLOSE_GANGLION_ARCHIVE      1501
#define IDC_CQ_AF3                      1502
#define IDC_REC_GANGLION_ARCHIVE        1502
#define IDC_CQ_F7                       1503
#define IDC_END_GANGLION_RECORDING      1503
#define IDC_CQ_F3                       1504
#define IDC_GANGLION_ARCHIVE_NAME       1504
#define IDC_DISCONNECT_GANGLION         1505
#define IDC_AVERAGING                   1505
#define IDC_CQ_FC5                      1506
#define IDC_START_DATA                  1506
#define IDC_OSCICAPTION                 1506
#define IDC_CQ_T7                       1507
#define IDC_SELECT_GANGLION2            1507
#define IDC_SELECT_GANGLION             1507
#define IDC_CONNECT_GANGLION            1507
#define IDC_OSCIFILENAME                1507
#define IDC_STOPWHENFINISH              1507
#define IDC_CQ_P7                       1508
#define IDC_STOP_DATA                   1508
#define IDC_SESSIONTIME                 1508
#define IDC_CQ_O1                       1509
#define IDC_STOP_IMPEDANCECHECK         1509
#define IDC_SESSIONLIST                 1509
#define IDC_NEXTCONFIGNAME              1509
#define IDC_CQ_O2                       1510
#define IDC_START_IMPEDANCECHECK        1510
#define IDC_WNDCAPTION                  1510
#define IDC_COUNTDOWN                   1510
#define IDC_MENU_X                      1510
#define IDC_CQ_P8                       1511
#define IDC_DISPLAYNAVIGATION           1511
#define IDC_GANGLION_BLEDONGLECOMBO     1511
#define IDC_CQ_T8                       1512
#define IDC_NEXTCONFIG                  1512
#define IDC_LOGOPATH                    1512
#define IDC_CQ_FC6                      1513
#define IDC_LOADNEXTCONFIG              1513
#define IDC_WINDOWCAPTION2              1513
#define IDC_WINDOWCAPTION               1513
#define IDC_CQ_F4                       1514
#define IDC_INTERVALUNIT                1514
#define IDC_MENU_Y                      1514
#define IDC_CQ_F8                       1515
#define IDC_FINDCODE                    1515
#define IDC_LOGO_X                      1515
#define IDC_CQ_AF4                      1516
#define IDC_ACTKEY                      1516
#define IDC_LOGO_Y                      1516
#define IDC_WIRELESS_QUALITY            1517
#define IDC_REPLACECODE                 1517
#define IDC_NAVCROSS_X                  1517
#define IDC_BATTERY_LIFE                1518
#define IDC_MODEBOX                     1518
#define IDC_NAVCROSS_Y                  1518
#define IDC_BATTERY_CHARGE_LEVEL        1519
#define IDC_BUTTONPATH                  1519
#define IDC_TRANSCOL                    1520
#define IDC_DISPLAYBORDER               1521
#define IDC_VALUE1                      1522
#define IDC_VALUE2                      1523
#define IDC_FUNCTIONCOMBO               1524
#define IDC_BUTTONCAPTION               1525
#define IDC_EDIT_WINDOW                 1525
#define IDC_LOCK_WINDOW                 1526
#define IDC_STARTSTOP                   1527
#define IDC_BLOCK_INVALID_VALUE         1528
#define IDC_ONLY_CHANGING               1529
#define IDC_TRUE_VALUE                  1530
#define IDC_FALSE_VALUE                 1531
#define IDC_TRUECOMBO                   1532
#define IDC_FALSECOMBO                  1533
#define IDC_UPPERMODE_COMBO             1534
#define IDC_UPPERMODE_COMBO2            1535
#define IDC_LOWERMODE_COMBO             1535
#define IDC_BIOSEMI_UPDATEBOX           1557
#define IDC_BIOSEMI_UPDATE_STATUS       1559
#define IDC_BUTTON1                     1560
#define IDC_BIOSEMI_CANCEL              1560
#define IDC_BIOSEMI_TenTwenty           1561
#define IDC_BIOSEMI_ABC                 1562
#define IDC_BIOSEMI_APPLY_SELECTION     1563
#define IDC_BIOSEMI_UPDATE_STATUS2      1564
#define IDC_BIOSEMI_APPLY_STATUS        1564
#define IDC_BIOSEMI_MEM                 1565
#define IDC_BIOSEMI_MEM2                1566
#define IDC_BIOSEMI_MAXMIN              1566
#define IDC_BF_DEVICECOMBO              1566
#define IDC_BF_APPLY_DEVICE             1567
#define IDC_BF_ARCHIVEFILE              1568
#define IDC_OPEN_BF_ARCHIVE             1569
#define IDC_CLOSE_BF_ARCHIVE            1570
#define IDC_REC_BF_ARCHIVE              1571
#define IDC_END_BF_RECORDING            1572
#define IDC_BF_SERIALPORT               1573
#define IDC_BF_IPADDRESS                1574
#define IDC_BF_IPPORT                   1575
#define IDC_BF_MACADDRESS               1577
#define IDC_SHOW_POSITIONS2             1578
#define IDC_SHOW_POSITION               1578
#define IDC_BF_CONFIG                   1579
#define IDC_BF_CONFIG2                  1580
#define IDC_BF_TIMEOUT                  1580
#define IDM_SETTINGS                    32771
#define IDM_LOADCONFIG                  32779
#define IDM_SAVECONFIG                  32780
#define IDM_INSERTSPECTRUM              32790
#define IDM_INSERTMIDI                  32791
#define IDM_INSERTTHRESHOLD             32792
#define IDM_INSERTPARTICLE              32793
#define IDM_INSERTOSCI                  32795
#define IDM_INSERTSIGNAL                32796
#define IDM_INSERTTRANSLATE             32797
#define IDM_INSERTMAGNITUDE             32798
#define IDM_EDITCOLORS                  32800
#define IDM_EDITSCALES                  32801
#define IDM_INSERTAND                   32802
#define IDM_INSERTWAV                   32803
#define IDM_INSERTOR                    32805
#define IDM_INSERTNOT                   32806
#define IDM_INSERTTCPRECEIVER           32807
#define IDM_INSERTFILTER                32808
#define IDM_NEUROSERVER                 32813
#define IDM_READEDF                     32814
#define IDM_INSERTDOKU                  32816
#define IDM_INSERTEVAL                  32817
#define IDM_INSERTAVI                   32818
#define IDM_INSERTAVERAGE               32819
#define IDM_INSERTCORR                  32820
#define IDM_NEWCONFIG                   32821
#define IDM_INSERTEDFREADER             32822
#define IDM_INSERTTCPSENDER             32823
#define IDM_INSERTEDFWRITER             32824
#define IDM_INSERTCOMPARE               32825
#define IDM_INSERTBALLGAME              32826
#define IDM_INSERTMIXER4                32827
#define IDM_INSERTMOUSE                 32828
#define IDM_INSERTMODEEG                32829
#define IDM_PLAY                        32830
#define IDM_STOP                        32831
#define IDM_INSERTERPDETECT             32833
#define IDM_INSERTCOM_WRITER            32834
#define IDM_INSERTCAM                   32835
#define IDM_INSERTCONSTANT              32836
#define IDM_INSERTINTEGRATE             32837
#define IDM_INSERTDEBOUNCE              32838
#define IDM_INSERTSAMPLE_HOLD           32839
#define IDM_INSERTMATLAB                32840
#define IDM_INSERTCOUNTER               32841
#define IDM_INSERTSKINDIALOG            32842
#define IDM_INSERTFILE_WRITER           32844
#define IDM_INSERTDEVIATION             32845
#define IDM_INSERTMCIPLAYER             32846
#define IDM_INSERTDEMO                  32847
#define IDM_INSERTKEYSTRIKE             32848
#define IDM_INSERTPEAKDETECT            32849
#define IDM_HELP                        32850
#define IDM_INSERTSPELLER               32851
#define IDM_INSERTMARTINI               32852
#define IDM_INSERTFILE_READER           32853
#define IDM_INSERTPORT_IO               32854
#define IDM_INSERTARRAY3600             32855
#define IDM_INSERTCOMREADER             32856
#define IDM_INSERTCAM2                  32858
#define ID_SOURCE_NEUROBITOPTIMA        32859
#define IDM_INSERTOPTIMA                32860
#define ID_HELP_VIEWLASTLOGFILE         32861
#define IDM_VIEWLASTLOGFILE             32862
#define ID_EDIT_COPYSELECTEDELEMENT     32863
#define ID_EDIT_PASTE                   32864
#define IDM_COPY                        32865
#define IDM_PASTE                       32866
#define ID_PROCESSING_MIN               32867
#define ID_PROCESSING_MAX               32868
#define ID_PROCESSING_ROUND             32869
#define ID_PROCESSING_DIFFERENTIATE     32870
#define ID_PROCESSING_DELAY             32871
#define ID_PROCESSING_LIMITER           32872
#define IDM_INSERTMAX                   32873
#define IDM_INSERTMIN                   32874
#define IDM_INSERTROUND                 32875
#define IDM_INSERTLIMITER               32876
#define IDM_INSERTDELAY                 32877
#define IDM_INSERTDIFFERENTIATE         32878
#define ID_OPTIONS_APPLICATION          32879
#define ID_OPTIONS_DEVICESETTINGS       32880
#define IDM_DEVICEWINDOW                32881
#define IDM_DEVICESETTINGS              32882
#define ID_SOURCE_EMOTIVEPOCHEADSET     32883
#define ID_SOURCE_BIOSIGNAL             32883
#define IDM_EMOTIV                      32884
#define ID_SOURCE_BIOSIGNAL32884        32884
#define IDM_INSERTEMOTIV                32885
#define IDM_FLOATVECTOR                 32886
#define ID_PROCESSING_VECTOR            32887
#define IDM_VECTORFLOAT                 32888
#define IDM_INSERT_FLOATVECTOR          32889
#define IDM_INSERT_VECTORFLOAT          32890
#define ID_TARGET_DISPLAYVECTOR         32891
#define IDM_INSERT_DISPLAYVECTOR        32892
#define IDM_INSERTFLOATVECTOR           32893
#define IDM_INSERTVECTORFLOAT           32894
#define IDM_INSERTDISPLAYVECTOR         32895
#define IDM_INSERTVECTORBUFFER          32896
#define ID_BIOSIGNAL_OPENEEG            32897
#define IDM_INSERTEEGP2                 32898
#define IDM_INSERT_EEG_P2               32899
#define ID_BIOSIGNAL_OPENEEG32900       32900
#define ID_BIOSIGNAL_OCZNIA             32901
#define IDM_INSERT_EEG_P21              32902
#define IDM_INSERT_EEG_NIA              32903
#define ID_BIOSIGNAL_PENDANTEEG         32904
#define IDM_INSERT_EEG_PENDANT          32905
#define ID_BIOSIGNAL_QDS                32906
#define IDM_INSERT_EEG_QDS              32907
#define ID_BIOSIGNAL_SMARTBRAINTECHNOLOGIES 32908
#define IDM_INSERT_EEG_SBT4CHN          32909
#define ID_BIOSIGNAL_SMARTBRAINTECHNOLOGIES32910 32910
#define IDM_INSERT_EEG_SBTBT            32911
#define ID_BIOSIGNAL_OPENBCI            32912
#define IDM_INSERT_EEG_OPENBCI4CHN      32913
#define ID_BIOSIGNAL_IBVA               32914
#define IDM_INSERT_EEG_IBVA             32915
#define IDM_INSERT_EEG_GENERIC8Bit      32916
#define ID_BIOSIGNAL_GENERIC            32917
#define IDM_INSERT_EEG_GENERIC16BIT     32918
#define ID_BIOSIGNAL_MONOLITHEEG        32919
#define IDM_INSERT_EEG_GENERIC8         32920
#define IDM_INSERT_EEG_GENERIC16        32921
#define IDM_INSERT_EEG_OPENBCI8         32922
#define IDM_INSERT_EEG_SBT4             32923
#define IDM_INSERT_EEG_SBT2             32924
#define IDM_INSERT_EEG_P3               32925
#define ID_BIOSIGNAL_OPITRUESENSEEXPLORATIONKIT 32926
#define IDM_INSERT_EEG_OPI_EXPLORATION  32927
#define ID_TARGET_COM                   32928
#define IDM_INSERT_COMWRITER2           32929
#define ID_BIOSIGNAL_OPENBCI32930       32930
#define IDM_INSERT_EEG_OPENBCI16        32931
#define ID_BIOSIGNAL_OPENBCIGANGLION    32932
#define IDM_INSERT_GANGLION             32933
#define IDM_INSERTGANGLION              32934
#define ID_BIOSIGNAL_NEUROSKY           32935
#define IDM_INSERT_EEG_NEUROSKY         32936
#define ID_OTHERS_STOPSESSION           32937
#define IDM_INSERT_STOPSESSION          32938
#define IDM_INSERTSESSIONTIME           32939
#define ID_OTHERS_SESSIONMANAGER        32940
#define IDM_INSERT_SESSIONMANAGER       32941
#define IDM_INSERTSESSIONMANAGER        32942
#define ID_EDIT_PASTEELEMENT            32943
#define ID_EDIT_COPYELEMENT             32944
#define IDM_COPYPASTE                   32945
#define ID_SOURCE_KEYCAPTURE            32946
#define IDM_INSERTKEYCAPTURE            32947
#define ID_OTHERS_BUTTON                32948
#define IDM_INSERTBUTTON                32949
#define IDM_INSERTEVAL_EXPRTK           32950
#define IDM_INSERTSHADOW                32951
#define ID_TARGET_VOLUME                32952
#define IDM_INSETVOLUME                 32953
#define ID_TARGET_OSC                   32954
#define IDM_INSERTOSCSENDER             32955
#define IDM_INSERTVOLUME                32956
#define ID_TARGET_THRESHOLD             32957
#define IDM_INSERT_THRESHOLD            32958
#define ID_Menu                         32959
#define ID_SOURCE_BIOSEMIACTIVETWO      32960
#define ID_BIOSIGNAL_BIOSEMIACTIVETWO   32961
#define IDM_BIOSIGNAL_BIOSEMIACTIVETWO  32962
#define IDM_INSERT_EEG_BIOSEMI          32963
#define ID_TOOLS_TESTBRAINFLOW          32964
#define IDM_TESTBRAINFLOW               32965
#define IDM_TEST_BRAINFLOW              32966
#define ID_BIOSIGNAL_BRAINFLOW          32967
#define IDM_BRAINFLOW                   32968
#define IDM_INSERT_BRAINFLOW            32969
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        270
#define _APS_NEXT_COMMAND_VALUE         32970
#define _APS_NEXT_CONTROL_VALUE         1580
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
